### ISSUE TITLE
Create logotype

### ISSUE THREAD

**Issue by JonasHallFnx** [FortnoxAB/reactive-wizard#15]

**Comment by splitfeed** [comment]
Hi Richard!

Sorry about the late response, we've been off on vacations :)

Off the top of my head, reactive-wizard is in large a product of using Reactive X (http://reactivex.io/) and concepts from Drop Wizard (https://www.dropwizard.io). I'm not asking for some cut n paste job, but it might be cool if we could make something that someone could realize that it's actually related to those. Some kind of spiritual merge of the two :)
What do you think?

**Comment by richardbmx** [comment]
@splitfeed  Perfect I will work on some samples and I present them to you

**Comment by richardbmx** [comment]
@splitfeed Hello friend, I apologize for the delay that I had problems with the Internet connection.

Here I present my proposal with some minimum variations, the design is inspired by the fusion of the two logos that are in the link that you sent me to relate to it but looking for identity for your project, I use the magician's base but with its own personality this gives a modern and minimalist and aggressive logo that gives a special touch to your project, I hope you like it if you want some change you just have to ask for it, I will gladly do it. Greetings :-)

![logo101](https://user-images.githubusercontent.com/35604837/45260340-02113480-b3b3-11e8-9ccb-57d2a0b266d6.png)

**Comment by splitfeed** [comment]
@richardbmx These look awesome! What do you think about turning down the aggressiveness on the wizard himself a bit? It looks great otherwise so a small adjustment on perhaps the eyes would do :)

Again, thank you so much for helping us with this!

**Comment by richardbmx** [comment]
@splitfeed I present these two versions of eyes less aggressive than the previous

![cambio ojos](https://user-images.githubusercontent.com/35604837/45363048-73fca000-b5a4-11e8-8965-14d4dc36a200.png)

**Comment by MartinStengard** [comment]
@richardbmx Just a thought, have you tried putting on some cool round glasses? Think first edition (the aggressive eyes) do get much more character but maybe a pair of Harry Potter glasses do the trick of friendly character?

**Comment by richardbmx** [comment]
@MartinStengard  Here is a version with glasses

![ojos con lestes](https://user-images.githubusercontent.com/35604837/45387376-e6d93b80-b5e3-11e8-92d7-2c9f2a592ee5.png)

**Comment by JonasHallFnx** [comment]
@richardbmx thank you very much for your contribution! Now we have alot of logos to choose from. How are the terms for using your logos? Is there any license? Any restrictions? Any fees?

**Comment by richardbmx** [comment]
@JonasHallFnx  Perfect, you must tell me what logo you want for me to generate a folder with all the necessary files to use it, all my designs are under a Creative Commons 4.0 license that allows free use of each and every one of the designs, there is no charge for my logos I can give credit in the readme file of the project and that's enough

**Comment by richardbmx** [comment]
@JonasHallFnx  @splitfeed  Happy day for everyone. Have you decided which of all the versions you want to use? is to believe the folder with all the designs so that they can use it.

**Comment by JonasHallFnx** [comment]
@richardbmx , we decided to proceed with another logo. We really appreciate the time you took to work with us and wish you the best in the future!
