### ISSUE TITLE
CollectionOptions from request

### ISSUE THREAD

**Issue by magnusp** [FortnoxAB/reactive-wizard#152]
The dao module has an CollectionOptions class but the resolver from request parameters hasn't been ported or adapted yet.

**Comment by JonasHallFnx** [comment]
I think we should use `@BeanParam` when we make the OSS implementation of this, instead of using a resolver. Sounds good?

**Comment by magnusp** [comment]
> I think we should use `@BeanParam` when we make the OSS implementation of this, instead of using a resolver. Sounds good?

Yup, sounds reasonable!

**Comment by rassmate** [comment]
Fixed
